@url = http://localhost:5000
@depositId = 7ecdc7c9-5754-4325-86d6-2ca533457f1c
@customerId = b0863a3c-ad16-43f1-b51d-6d8c82808ebc
@withdrawalIban = PL10105000997603123456789123


###
GET {{url}}/deposits/accounts

###
GET {{url}}/deposits

###
POST {{url}}/deposits
Content-Type: application/json

{
  "customerId": "{{customerId}}",
  "currency": "PLN",
  "amount": "1000"
}

###
PUT {{url}}/deposits/{{depositId}}/complete
Content-Type: application/json

{
  "depositId": "{{depositId}}",
  "secret": "secret"
}

###
GET {{url}}/withdrawals/accounts

###
POST {{url}}/withdrawals/accounts
Content-Type: application/json

{
  "currency": "PLN",
  "iban": "{{withdrawalIban}}"
}

###
GET {{url}}/withdrawals

###
POST {{url}}/withdrawals
Content-Type: application/json

{
  "currency": "PLN",
  "amount": "1000"
}