@url = http://localhost:5000
@depositId = 48755ba2-eb1c-4f77-b5bd-8802cb53eb36
@customerId = 5eacf848-e62a-4fa1-9e98-6527f3e91180

@withdrawalIban = PL10105000997603123456789123


###
GET {{url}}/deposits/accounts

###
GET {{url}}/deposits

###
POST {{url}}/deposits
Content-Type: application/json

{
  "customerId": "{{customerId}}",
  "currency": "PLN",
  "amount": "1000"
}

###
PUT {{url}}/deposits/{{depositId}}/complete
Content-Type: application/json

{
  "depositId": "{{depositId}}",
  "secret": "secret"
}

###
GET {{url}}/withdrawals/accounts

###
POST {{url}}/withdrawals/accounts
Content-Type: application/json

{
  "currency": "PLN",
  "iban": "{{withdrawalIban}}"
}

###
GET {{url}}/withdrawals

###
POST {{url}}/withdrawals
Content-Type: application/json

{
  "currency": "PLN",
  "amount": "1000"
}