@url = http://localhost:5000/customers
@customerId = 625ae92f-9689-41d0-bb9c-2f2bb046e714

###
GET {{url}}

###
GET {{url}}/{{customerId}}

###
POST {{url}}
Content-Type: application/json

{
  "email": "user6@inflow.io"
}

###
PUT {{url}}/complete
Content-Type: application/json

{
  "name": "user1",
  "fullName": "John Doe",
  "address": "Test street 123",
  "nationality": "PL",
  "identityType": "id_card",
  "identitySeries": "ABC1234567"
}

###
PUT {{url}}/{{customerId}}/verify
Content-Type: application/json

{
}

###
PUT {{url}}/{{customerId}}/lock
Content-Type: application/json

{
}

###
PUT {{url}}/{{customerId}}/unlock
Content-Type: application/json

{
}