@url = http://localhost:5000/customers
@customerId = 5fcb1328-3a66-49eb-907a-db0a575b4970

###
GET {{url}}

###
GET {{url}}/{{customerId}}

###
POST {{url}}
Content-Type: application/json

{
  "email": "user6@inflow.io"
}

###
PUT {{url}}/complete
Content-Type: application/json

{
  "name": "user10",
  "fullName": "Patryk Moore",
  "address": "Baker Street 78",
  "nationality": "PL",
  "identityType": "id_card",
  "identitySeries": "AER6756855"
}

###
PUT {{url}}/{{customerId}}/verify
Content-Type: application/json

{
}

###
PUT {{url}}/{{customerId}}/lock
Content-Type: application/json

{
}

###
PUT {{url}}/{{customerId}}/unlock
Content-Type: application/json

{
}