@url = http://localhost:5000/customers
@customerId = d7f0780e-05d7-43bd-986e-c803728cfccb

###
GET {{url}}

###
GET {{url}}/{{customerId}}

###
POST {{url}}
Content-Type: application/json

{
  "email": "user6@inflow.io"
}

###
PUT {{url}}/complete
Content-Type: application/json

{
  "customerId": "{{customerId}}",
  "name": "user3",
  "fullName": "Victor Wu",
  "address": "Baker street 420",
  "nationality": "PL",
  "identityType": "id_card",
  "identitySeries": "ABC6756667"
}

###
PUT {{url}}/{{customerId}}/verify
Content-Type: application/json

{
}

###
PUT {{url}}/{{customerId}}/lock
Content-Type: application/json

{
}

###
PUT {{url}}/{{customerId}}/unlock
Content-Type: application/json

{
}